version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
      exclude:
        - "no.nav.*"
    groups:
      nav-deps:
        patterns:
          - "*no.nav*"
        exclude-patterns:
          - "*no.nav.security*"
      nav-security-deps:
        patterns:
          - "*no.nav.security*"
      spring-deps:
        patterns:
          - "*spring*"
      annet-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "*spring*"
          - "*no.nav*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
