spring:
  application:
    name: # Settes i nais/<cluster>.json

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 2
      connection-timeout: 1000
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus
      path-mapping:
        prometheus: /metrics
