spring:
  application:
    name: # Settes i nais/<cluster>.json

  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 2
      connection-timeout: 1000
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      group-id: ${SPRING_APPLICATION_NAME}
      auto-offset-reset: earliest
      isolation-level: read_committed
      enable-auto-commit: false
    producer:
      client-id: ${HOSTNAME}
      retries: 3
      transaction-id-prefix: -tx

topic:
  # Bryter betegner av/på funksjon for kafkalytter. True (på), False (av).
  listener:
    # topic.listener.ung-soknad
    ung-soknad:
      id: ungdomsytelsesoknad-listener
      navn: dusseldorf.ungdomsytelse-soknad-cleanup
      bryter: true
      auto-offset-reset: latest

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus
      path-mapping:
        prometheus: /metrics

no.nav:
  security:
    jwt:
      issuer:
        tokenx:
          discoveryUrl: ${TOKEN_X_WELL_KNOWN_URL}
          accepted_audience: ${TOKEN_X_CLIENT_ID}
        azure:
          discoveryUrl: ${AZURE_APP_WELL_KNOWN_URL}
          accepted_audience: ${AZURE_APP_CLIENT_ID}
      client:
        registration:
          azure-k9-sak:
            token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            grant-type: client_credentials
            scope: ${K9_SAK_AZURE_SCOPE}
            authentication:
              client-auth-method: private_key_jwt
              client-id: ${AZURE_APP_CLIENT_ID}
              client-jwk: ${AZURE_APP_JWK}

          azure-pdl-api:
            token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            grant-type: client_credentials
            scope: ${PDL_API_AZURE_SCOPE}
            authentication:
              client-auth-method: private_key_jwt
              client-id: ${AZURE_APP_CLIENT_ID}
              client-jwk: ${AZURE_APP_JWK}

  gateways:
    k9-sak: # Settes i nais/<cluster>.json
    pdl-api-base-url: # Settes i nais/<cluster>.json

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
    disable-swagger-default-url: true
    path: swagger-ui.html
