management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  mvc:
    log-request-details: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
