management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  mvc:
    log-request-details: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  kafka:
    producer:
      transaction-id-prefix: -tx
    security:
      protocol: SSL
    ssl:
      trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
      trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}
      trust-store-type: JKS
      key-store-location: file:${KAFKA_KEYSTORE_PATH}
      key-store-password: ${KAFKA_CREDSTORE_PASSWORD}
      key-store-type: PKCS12

PROGRAM_OPPSTART_DATO: 2025-01-01
