# This workflow trigger on push to any branch.
name: Alerts
on:
  push:
    paths:
      - 'nais/alerts.yml'
      - 'nais/dev-gcp.json'
      - 'nais/prod-gcp.json'
      - '.github/workflows/apply-alerts.yml'
    branches:
      - 'main'
      - 'dev-**'

jobs:
  deploy-dev-gcp:
    name: Deploy to dev-gcp
    if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/main') # Deploy if branch is either main or dev-*
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/alerts.yml
          VARS: nais/dev-gcp.json

  deploy-prod-gcp:
    name: Deploy to prod-gcp
    if: startsWith(github.ref, 'refs/heads/main')  # If the branch is main
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/alerts.yml
          VARS: nais/prod-gcp.json
