# This workflow trigger on push to any branch.
name: Build
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.github/workflows/apply-alerts.yml'
      - 'nais/alerts.yml'
    branches:

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-build-app.yml@main
    with:
      java-version: 21
      build-image: ${{ github.actor != 'dependabot[bot]' }}
      push-image: ${{ github.ref_name == github.event.repository.default_branch}}
      upload-image: ${{ github.ref_name != github.event.repository.default_branch }}
    secrets: inherit

  trivy:
    needs: [ build-app ]
    if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/main') || github.event.deployment.payload.triggered # Build and push docker if branch is either main or dev-*
    uses: navikt/sif-gha-workflows/.github/workflows/trivy.yml@main
    permissions:
      contents: write
      security-events: write
      id-token: write
      actions: read
    secrets: inherit
    with:
      image: ${{ needs.build-app.outputs.image }}
      team: k9saksbehandling

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
      contents: write
    if: github.ref_name == 'main'
    needs: build-app
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      naiserator_file: nais/naiserator.yaml
      input_vars_file: nais/dev-gcp.json
    secrets: inherit

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
      contents: write
    if: github.ref_name == 'main'
    needs: [ build-app, deploy-dev ]
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      naiserator_file: nais/naiserator.yaml
      input_vars_file: nais/prod-gcp.json
    secrets: inherit
