# This workflow trigger on push to any branch.
name: Build
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.github/workflows/apply-alerts.yml'
      - 'nais/alerts.yml'
    branches:

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-build-app.yml@main
    with:
      java-version: 21
      build-image: ${{ github.actor != 'dependabot[bot]' }}
      push-image: ${{ startsWith(github.ref, 'refs/heads/dev-') ||  github.ref_name == github.event.repository.default_branch }}
      upload-image: ${{ !startsWith(github.ref, 'refs/heads/dev-') &&  github.ref_name != github.event.repository.default_branch }}
      additional-tag: ${{ startsWith(github.ref, 'refs/heads/dev-') && 'latest-dev' }}
    secrets: inherit

  verdikjede-tester:
    name: Verdikjedetester
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      packages: read
    uses: navikt/sif-gha-workflows/.github/workflows/verdikjede-test-v2.yml@main
    if: ${{github.actor != 'dependabot[bot]'}}
    needs: build-app
    with:
      tag: ${{ needs.build-app.outputs.build-version }}
      suites: "ung"
      override_image_artifact_name: ${{ !startsWith(github.ref, 'refs/heads/dev-')  && github.ref_name != github.event.repository.default_branch && needs.build-app.outputs.image-artifact-name || null }}
      image_version: ${{ needs.build-app.outputs.build-version }}


  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
      contents: write
    if: startsWith(github.ref, 'refs/heads/dev-') || github.ref_name == github.event.repository.default_branch # Build and push docker if branch is either main or dev-*
    needs: build-app
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      naiserator_file: nais/naiserator.yaml
      input_vars_file: nais/dev-gcp.json
    secrets: inherit

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
      contents: write
    if: github.ref_name == 'main'
    needs: [ build-app, deploy-dev, verdikjede-tester ]
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      naiserator_file: nais/naiserator.yaml
      input_vars_file: nais/prod-gcp.json
    secrets: inherit
