
name: Publish kontrakt
on:
  release:
    types: [published]

jobs:
  build:
    name: Bygg pull-request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Publish artifacts
        shell: bash
        run: |
          mvn deploy -e -B --settings ./.m2/settings.xml -am -pl kontrakt -DtrimStackTrace=false -Dchangelist= -Dsha1= -Drevision=$NEW_VERSION -Dfile.encoding=UTF-8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ github.event.release.tag_name }}
